import { createClient } from '@/lib/supabase/server'
import { NextRequest, NextResponse } from 'next/server'
import PDFDocument from 'pdfkit'

function generateCertificatePDF(job: any): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margin: 50,
    })
    
    const chunks: Buffer[] = []
    
    doc.on('data', (chunk: Buffer) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)
    
    // Header
    doc.fontSize(28).font('Helvetica-Bold').text('GREEN CERTIFICATE', { align: 'center' })
    doc.moveDown(0.5)
    doc.fontSize(12).font('Helvetica').text('Carbon-Aware Code Execution Report', { align: 'center' })
    doc.moveDown(1)
    
    // Separator line
    doc.strokeColor('#2ecc71').lineWidth(2).moveTo(50, doc.y).lineTo(545, doc.y).stroke()
    doc.moveDown(1)
    
    // Job Details
    doc.fontSize(14).font('Helvetica-Bold').text('Execution Details', { underline: true })
    doc.moveDown(0.3)
    doc.fontSize(11).font('Helvetica')
    
    doc.text(`Job ID: ${job.id}`, { textIndent: 10 })
    doc.text(`Status: ${job.status.toUpperCase()}`, { textIndent: 10 })
    doc.text(`Priority: ${job.priority.charAt(0).toUpperCase() + job.priority.slice(1)}`, { textIndent: 10 })
    
    doc.moveDown(0.5)
    
    // Grid Carbon Intensity
    doc.fontSize(14).font('Helvetica-Bold').text('Grid Carbon Intensity', { underline: true })
    doc.moveDown(0.3)
    doc.fontSize(11).font('Helvetica')
    
    const carbonIntensity = job.grid_intensity_at_execution || 'N/A'
    const maxThreshold = job.max_carbon_intensity
    doc.text(`Current Intensity: ${carbonIntensity} gCO2eq/kWh`, { textIndent: 10 })
    doc.text(`Max Threshold: ${maxThreshold} gCO2eq/kWh`, { textIndent: 10 })
    
    const gridStatus = carbonIntensity !== 'N/A' && carbonIntensity <= maxThreshold ? 'GREEN ✓' : 'DELAYED'
    doc.text(`Status: ${gridStatus}`, { textIndent: 10 })
    
    doc.moveDown(0.5)
    
    // Execution Timing
    doc.fontSize(14).font('Helvetica-Bold').text('Execution Timing', { underline: true })
    doc.moveDown(0.3)
    doc.fontSize(11).font('Helvetica')
    
    const startTime = job.execution_start_time ? new Date(job.execution_start_time) : null
    const endTime = job.execution_end_time ? new Date(job.execution_end_time) : null
    
    if (startTime) {
      doc.text(`Start Time: ${startTime.toLocaleString()}`, { textIndent: 10 })
    }
    if (endTime) {
      doc.text(`End Time: ${endTime.toLocaleString()}`, { textIndent: 10 })
    }
    if (startTime && endTime) {
      const duration = Math.round((endTime.getTime() - startTime.getTime()) / 1000)
      doc.text(`Duration: ${duration} seconds`, { textIndent: 10 })
    }
    
    doc.moveDown(0.5)
    
    // Inferred Imports
    if (job.inferred_imports && job.inferred_imports.length > 0) {
      doc.fontSize(14).font('Helvetica-Bold').text('Detected Frameworks', { underline: true })
      doc.moveDown(0.3)
      doc.fontSize(11).font('Helvetica')
      
      job.inferred_imports.forEach((imp: string) => {
        doc.text(`• ${imp}`, { textIndent: 20 })
      })
      
      doc.moveDown(0.5)
    }
    
    // Console Output
    if (job.stdout) {
      doc.fontSize(14).font('Helvetica-Bold').text('Execution Output', { underline: true })
      doc.moveDown(0.3)
      doc.fontSize(9).font('Courier')
      
      const lines = job.stdout.split('\n').slice(0, 20) // Limit to first 20 lines
      lines.forEach((line: string) => {
        if (line.trim()) {
          doc.text(line, { textIndent: 10, width: 450 })
        }
      })
      
      if (job.stdout.split('\n').length > 20) {
        doc.text('... (output truncated for PDF)', { textIndent: 10, italic: true })
      }
      
      doc.moveDown(0.5)
    }
    
    if (job.stderr) {
      doc.fontSize(14).font('Helvetica-Bold').text('Errors', { underline: true })
      doc.moveDown(0.3)
      doc.fontSize(9).font('Courier').fillColor('red')
      
      const lines = job.stderr.split('\n').slice(0, 10)
      lines.forEach((line: string) => {
        if (line.trim()) {
          doc.text(line, { textIndent: 10, width: 450 })
        }
      })
      
      doc.moveDown(1)
    }
    
    // Footer
    doc.moveUp(0.5)
    doc.fontSize(10).fillColor('gray').text('Generated by Carbon-Aware Execution Platform', { align: 'center' })
    doc.text(`${new Date().toLocaleString()}`, { align: 'center' })
    
    doc.end()
  })
}

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { id } = params
    const supabase = createClient()
    
    // Fetch the job
    const { data: jobData, error } = await supabase
      .from('jobs')
      .select('*')
      .eq('id', id)
      .single()
    
    if (error || !jobData) {
      return NextResponse.json(
        { error: 'Job not found' },
        { status: 404 }
      )
    }
    
    // Generate PDF
    const pdfBuffer = await generateCertificatePDF(jobData)
    
    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="green-certificate-${jobData.id}.pdf"`,
      },
    })
  } catch (error) {
    console.error('[v0] Error generating certificate:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
